language: python
python:
  - "2.7"

addons:
  sauce_connect:
    username: SergioRM
  jwt:
    secure: travis encrypt SAUCE_ACCESS_KEY

install:
  - pip install -r requirements.txt

before_script:
  - nohup python code/application.py &>/dev/null &

script:
  - nosetests tests/tests_text_analyzer.py
  - nosetests tests/tests_db_connection.py
  - lettuce tests/features