language: python
python:
  - "2.7"

addons:
  sauce_connect:
    username: SergioRM
  jwt:
    secure: travis encrypt SAUCE_ACCESS_KEY=1f256b16-d392-439f-9cec-899ca4666f74

install:
  - pip install -r requirements.txt

before_script:
  - export SAUCE_USERNAME=SergioRM
  - export SAUCE_ACCESS_KEY=1f256b16-d392-439f-9cec-899ca4666f74
  - nohup python code/application.py &>/dev/null &

script:
  - nosetests tests/tests_text_analyzer.py
  - nosetests tests/tests_db_connection.py
  - lettuce tests/features